version: 2
jobs:
   build:
        docker:
            - image: circleci/node:10.15.3
        steps:
            - checkout
            - run: npm ci
            - run: npm run build
            - run: echo "Complete build"
   deploy:
        docker:
            - image: circleci/node:10.15.3
        steps:
            - checkout
            - run: npm run deploy
            - run: echo "Complete deploy"

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build # Only run deploy job once the build job has completed