version: 2
jobs:
   build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm ci
            - run: prettier src/**/*.{js,jsx} --write && node_modules/.bin/eslint src/**/*.{js,jsx} --fix
            - run: prettier src/**/*.css --write && node_modules/.bin/stylelint src/**/*.css --fix
            - run: echo "Complete"

   workflows:
        version: 2
        deploy:
            jobs:
                - build
                - deploy:
                    requires:
                        - build # Only run deploy job once the build job has completed
                    filters:
                        branches:
                            only:
                            - master